language: python

os:
  - linux
  - osx

python:
  - "pypy"
  - "2.6"
  - "2.7"

install:
  - pip install --verbose .
  - pip install --verbose unittest2

script:
  - unit2 -v OpenSSL.test.test_rand OpenSSL.test.test_crypto OpenSSL.test.test_ssl
