language: python

os:
  - linux
  - osx

python:
  - "pypy"
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"

install:
  - pip install --verbose .
  - pip install --verbose unittest2

script:
  - python setup.py test
