language: python

os:
  - linux
  - osx

python:
  - "pypy"
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"

env:
  - TOX_ENV=pypy
  - TOX_ENV=py26
  - TOX_ENV=py27
  - TOX_ENV=py32
  - TOX_ENV=py33

install:
  - pip install tox

script:
  - tox -e "${TOX_ENV}"

