language: python

os:
  - linux
  - osx

python:
  - "2.7"
  - "3.3"

install:
  - pip install .
  - pip install unittest2

script:
  - python -m unittest2 OpenSSL.test.test_rand OpenSSL.test.test_crypto OpenSSL.test.test_ssl
